# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Azure - Private Windows 2019 - Canada Central - XFA - Mise en place


steps:
- task: Go@0
  displayName: 'go build'
  inputs:
    command: build

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'sc-spxffadodev01'
    KeyVaultName: 'kvxffadodev01'

- task: CmdLine@2
  displayName: 'apps:exists'
  inputs:
    filename: 'dds-client'
    arguments: 'apps:exists --name dopsa'